require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeekreportsController do

  # This should return the minimal set of attributes required to create a valid
  # Weekreport. As you add validations to Weekreport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeekreportsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all weekreports as @weekreports" do
      weekreport = Weekreport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:weekreports).should eq([weekreport])
    end
  end

  describe "GET show" do
    it "assigns the requested weekreport as @weekreport" do
      weekreport = Weekreport.create! valid_attributes
      get :show, {:id => weekreport.to_param}, valid_session
      assigns(:weekreport).should eq(weekreport)
    end
  end

  describe "GET new" do
    it "assigns a new weekreport as @weekreport" do
      get :new, {}, valid_session
      assigns(:weekreport).should be_a_new(Weekreport)
    end
  end

  describe "GET edit" do
    it "assigns the requested weekreport as @weekreport" do
      weekreport = Weekreport.create! valid_attributes
      get :edit, {:id => weekreport.to_param}, valid_session
      assigns(:weekreport).should eq(weekreport)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Weekreport" do
        expect {
          post :create, {:weekreport => valid_attributes}, valid_session
        }.to change(Weekreport, :count).by(1)
      end

      it "assigns a newly created weekreport as @weekreport" do
        post :create, {:weekreport => valid_attributes}, valid_session
        assigns(:weekreport).should be_a(Weekreport)
        assigns(:weekreport).should be_persisted
      end

      it "redirects to the created weekreport" do
        post :create, {:weekreport => valid_attributes}, valid_session
        response.should redirect_to(Weekreport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weekreport as @weekreport" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weekreport.any_instance.stub(:save).and_return(false)
        post :create, {:weekreport => {}}, valid_session
        assigns(:weekreport).should be_a_new(Weekreport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weekreport.any_instance.stub(:save).and_return(false)
        post :create, {:weekreport => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weekreport" do
        weekreport = Weekreport.create! valid_attributes
        # Assuming there are no other weekreports in the database, this
        # specifies that the Weekreport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Weekreport.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => weekreport.to_param, :weekreport => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested weekreport as @weekreport" do
        weekreport = Weekreport.create! valid_attributes
        put :update, {:id => weekreport.to_param, :weekreport => valid_attributes}, valid_session
        assigns(:weekreport).should eq(weekreport)
      end

      it "redirects to the weekreport" do
        weekreport = Weekreport.create! valid_attributes
        put :update, {:id => weekreport.to_param, :weekreport => valid_attributes}, valid_session
        response.should redirect_to(weekreport)
      end
    end

    describe "with invalid params" do
      it "assigns the weekreport as @weekreport" do
        weekreport = Weekreport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weekreport.any_instance.stub(:save).and_return(false)
        put :update, {:id => weekreport.to_param, :weekreport => {}}, valid_session
        assigns(:weekreport).should eq(weekreport)
      end

      it "re-renders the 'edit' template" do
        weekreport = Weekreport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weekreport.any_instance.stub(:save).and_return(false)
        put :update, {:id => weekreport.to_param, :weekreport => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weekreport" do
      weekreport = Weekreport.create! valid_attributes
      expect {
        delete :destroy, {:id => weekreport.to_param}, valid_session
      }.to change(Weekreport, :count).by(-1)
    end

    it "redirects to the weekreports list" do
      weekreport = Weekreport.create! valid_attributes
      delete :destroy, {:id => weekreport.to_param}, valid_session
      response.should redirect_to(weekreports_url)
    end
  end

end
